backend:
  name: github
  repo: Enigma10/gatsby-blog

media_folder: static/assets
public_folder: assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: date, label: Created At, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Post, widget: markdown }